blueprints/auth.py
from io import BytesIO

import pyotp
import pyqrcode
from flask import Blueprint, render_template, redirect, url_for, request, flash, session

from app import app
from helpers import hash_password, log_request_info
from models.otp import Otp
from models.user import User, Role
from validators import valid_session, valid_session_without2fa

auth = Blueprint('auth', __name__)


@auth.route('/login')
def login():
    log_request_info(request)

    if valid_session(session, log=False):
        return redirect(url_for('main.index'))

    return render_template('login.html')


@auth.route('/login', methods=['POST'])
def login_post():
    log_request_info(request)

    login = request.form.get('login')
    password = request.form.get('password')
    password = hash_password(password)

    user = User.get_by_login(login)

    if user is None or user.password != password:
        flash('Логин или пароль неверны, попробуйте снова.')
        app.logger.info(f"Неуспешная попытка входа с логином '{login}'")
        return redirect(url_for('auth.login'))

    session["user_id"] = user.id
    session["user_role"] = user.role
    session["username"] = user.login
    session["2fa"] = False

    # app.logger.info(f"Пользователь '{user.login}' успешно вошел в систему")
    # return redirect(url_for('main.profile'))

    return redirect(url_for('auth.login_2fa'))


@auth.route("/login_2fa")
def login_2fa():
    if not valid_session_without2fa(session, log=False):
        return redirect(url_for('auth.login'))

    if session["2fa"]:
        return redirect(url_for("main.profile"))

    otpdata = Otp.get(session["user_id"])
    need_register = otpdata is None

    return render_template("login2fa.html", need_register=need_register)


@auth.route('/qrcode2fa')
def qrcode2fa():
    if not valid_session_without2fa(session, log=False):
        return '', 404

    secret = pyotp.random_base32()
    session["2fa_secret"] = secret
    uri = pyotp.totp.TOTP(secret).provisioning_uri(name=session["username"], issuer_name='student_perf')
    url = pyqrcode.create(uri)
    stream = BytesIO()
    url.svg(stream, scale=5)
    return stream.getvalue(), 200, {
        'Content-Type': 'image/svg+xml',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0'}


@app.route("/login_2fa", methods=["POST"])
def login_2fa_form():
    if not valid_session_without2fa(session, log=False):
        return '', 404

    otpdata = Otp.get(session["user_id"])
    if otpdata is not None:
        session["2fa_secret"] = otpdata.secret
    secret = session["2fa_secret"]

    otp = request.form.get("otp")
    if pyotp.TOTP(secret).verify(otp):
        if otpdata is None:
            if not Otp.create(session["user_id"], secret):
                return redirect(url_for("auth.login"))

        session["2fa"] = True
        session.pop("2fa_secret")
        flash("Успешно", "success")
        return redirect(url_for("main.profile"))
    else:
        session.pop("2fa_secret")
        session.pop("2fa")
        flash("Неправильный одноразовый пароль", "danger")
        return redirect(url_for("auth.login"))


@auth.route('/logout', methods=['GET'])
def logout():
    log_request_info(request)

    if not valid_session(session):
        return redirect(url_for('auth.login'))

    app.logger.info(f"Пользователь '{session['username']}' вышел из системы")

    session.pop("user_id")
    session.pop("user_role")
    session.pop("username")
    session.pop("2fa")
    return redirect(url_for('auth.login'))

blueprints/manager_profile.py
from flask import Blueprint, render_template, request, session, url_for, redirect

from app import app
from helpers import hash_password, log_request_info
from models.discipline import Discipline
from models.group import Group
from models.group_discipline import GroupDiscipline
from models.speciality import Speciality
from models.student import Student
from models.teacher import Teacher
from models.user import Role, User
from validators import valid_session, valid_args

manager_profile = Blueprint('manager_profile', __name__)


@manager_profile.route('/manager_profile', methods=['GET'])
def profile():
    log_request_info(request)

    if not valid_session(session):
        return redirect(url_for('auth.login'))

    user_id = session['user_id']
    user_role = session['user_role']
    username = session['username']

    if user_role != Role.Admin:
        return redirect(url_for('main.index'))

    app.logger.info(f"Пользователь {user_id}:{username} зашел в профиль администратора")

    return render_template('manager_profile.html')


######################### students #################################

@manager_profile.route('/student_list', methods=['GET'])
def student_list():
    log_request_info(request)

    if not valid_session(session):
        return redirect(url_for('auth.login'))

    user_id = session['user_id']
    user_role = session['user_role']
    username = session['username']
    if user_role != Role.Admin:
        return redirect(url_for('main.index'))

    students = Student.get_all()
    data = []
    for student in students:
        full_name = ' '.join((student.last_name, student.first_name, student.patronymic))
        group = Group.get(student.group_id)
        group_name = "-" if group is None else group.group_name
        data.append({'id': student.id,
                     'name': full_name,
                     'group_id': student.group_id,
                     'group': group_name,
                     'date': student.admission_date})

    app.logger.info(f"Пользователь {user_id}:{username} запросил список студентов")

    return render_template('student_list.html', data=data)


@manager_profile.route('/edit_student_form/<student_id>', methods=['GET'])
def edit_student_form(student_id):
    log_request_info(request)

    if not valid_session(session):
        return redirect(url_for('auth.login'))

    user_id = session['user_id']
    user_role = session['user_role']
    username = session['username']
    if user_role != Role.Admin:
        return 'Недостаточно прав', 403

    student = Student.get(student_id)
    if student is None:
        return 'Студент не найден', 404

    user = User.get(student_id)
    if user is None:
        return 'Пользователь не найден', 404

    groups = Group.get_all()
    if groups is None or len(groups) == 0:
        return 'Группы не найдены', 404

    app.logger.info(f"Пользователь {user_id}:{username} запросил данные студента")

    return render_template('student_edit.html', student=student, user=user, groups=groups)


@manager_profile.route('/edit_student', methods=['POST'])
def edit_student():
    log_request_info(request)

    if not valid_session(session):
        return redirect(url_for('auth.login'))

    user_id = session['user_id']
    user_role = session['user_role']
    username = session['username']
    if user_role != Role.Admin:
        return 'Недостаточно прав', 403

    data = request.get_json(force=True)
    if not valid_args(data, 'id', 'first_name', 'last_name', 'group_id', 'patronymic', 'year'):
        return 'Некорректные данные', 500

    if not Student.update(id=data['id'],
                          first_name=data['first_name'],
                          last_name=data['last_name'],
                          patronymic=data['patronymic'],
                          group_id=data['group_id'],
                          admission_date=data['year']):
        return 'Не удалось обновить студента', 500

    app.logger.info(f"Пользователь {user_id}:{username} обновил данные студента")

    return 'Студент обновлен', 200


@manager_profile.route('/create_student_form', methods=['GET'])
def create_student_form():
    log_request_info(request)

    if not valid_session(session):
        return redirect(url_for('auth.login'))

    user_id = session['user_id']
    user_role = session['user_role']
    username = session['username']
    if user_role != Role.Admin:
        return 'Недостаточно прав', 403

    groups = Group.get_all()
    if groups is None or len(groups) == 0:
        return 'Группы не найдены', 404

    empty_student = Student(0)
    empty_student.group_id = groups[0].id

    empty_user = User(0)

    app.logger.info(f"Пользователь {user_id}:{username} запросил форму создания студента")

    return render_template('student_edit.html', student=empty_student, user=empty_user, groups=groups)


@manager_profile.route('/create_student', methods=['POST'])
def create_student():
    log_request_info(request)

    if not valid_session(session):
        return redirect(url_for('auth.login'))

    user_id = session['user_id']
    user_role = session['user_role']
    username = session['username']
    if user_role != Role.Admin:
        return 'Недостаточно прав', 403

    data = request.get_json(force=True)
    if not valid_args(data, 'first_name', 'last_name', 'group_id', 'login', 'password', 'patronymic', 'year'):
        return 'Некорректные данные', 500

    ok = Student.create(login=data["login"],
                        password=hash_password(data['password']),
                        first_name=data['first_name'],
                        last_name=data['last_name'],
                        patronymic=data['patronymic'],
                        admission_date=data['year'],
                        group_id=data['group_id'])

    if not ok:
        return 'Не удалось создать студента', 500

    app.logger.info(f"Пользователь {user_id}:{username} создал студента")

    return 'Студент создан', 200


@manager_profile.route('/delete_student/<student_id>', methods=['DELETE'])
def delete_student(student_id):
    log_request_info(request)

    if not valid_session(session):
        return redirect(url_for('auth.login'))

    user_id = session['user_id']
    user_role = session['user_role']
    username = session['username']
    if user_role != Role.Admin:
        return 'Недостаточно прав', 403

    print(f'Delete student {student_id}')

    if not Student.delete(student_id):
        return 'Не удалось удалить студента', 500

    app.logger.info(f"Пользователь {user_id}:{username} удалил студента")

    return 'Студент удален', 200


######################### teachers #################################

@manager_profile.route('/teacher_list', methods=['GET'])
def teacher_list():
    log_request_info(request)

    if not valid_session(session):
        return redirect(url_for('auth.login'))

    user_id = session['user_id']
    user_role = session['user_role']
    username = session['username']
    if user_role != Role.Admin:
        return redirect(url_for('main.index'))

    teachers = Teacher.get_all()
    data = []
    for t in teachers:
        full_name = ' '.join((t.last_name, t.first_name, t.patronymic))
        data.append({'id': t.id,
                     'name': full_name,
                     })

    app.logger.info(f"Пользователь {user_id}:{username} запросил список преподавателей")

    return render_template('teacher_list.html', teachers=data)


@manager_profile.route('/edit_teacher_form/<id>', methods=['GET'])
def edit_teacher_form(id):
    log_request_info(request)

    if not valid_session(session):
        return redirect(url_for('auth.login'))

    user_id = session['user_id']
    user_role = session['user_role']
    username = session['username']
    if user_role != Role.Admin:
        return 'Недостаточно прав', 403

    t = Teacher.get(id)
    if t is None:
        return 'Преподаватель не найден', 404

    user = User.get(id)
    if user is None:
        return 'Пользователь не найден', 404

    app.logger.info(f"Пользователь {user_id}:{username} запросил данные преподавателя")

    return render_template('teacher_edit.html', teacher=t, user=user)


@manager_profile.route('/edit_teacher', methods=['POST'])
def edit_teacher():
    log_request_info(request)

    if not valid_session(session):
        return redirect(url_for('auth.login'))

    user_id = session['user_id']
    user_role = session['user_role']
    username = session['username']
    if user_role != Role.Admin:
        return 'Недостаточно прав', 403

    data = request.get_json(force=True)
    if not valid_args(data, 'id', 'first_name', 'last_name', 'patronymic'):
        return 'Некорректные данные', 500

    if not Teacher.update(id=data['id'],
                          first_name=data['first_name'],
                          last_name=data['last_name'],
                          patronymic=data['patronymic']
                          ):
        return 'Не удалось обновить преподавателя', 500

    app.logger.info(f"Пользователь {user_id}:{username} обновил данные преподавателя")

    return 'Преподаватель обновлен', 200


@manager_profile.route('/create_teacher_form', methods=['GET'])
def create_teacher_form():
    log_request_info(request)

    if not valid_session(session):
        return redirect(url_for('auth.login'))

    user_id = session['user_id']
    user_role = session['user_role']
    username = session['username']
    if user_role != Role.Admin:
        return 'Недостаточно прав', 403

    empty_teacher = Teacher(0)
    empty_user = User(0)

    app.logger.info(f"Пользователь {user_id}:{username} запросил форму создания преподавателя")

    return render_template('teacher_edit.html', teacher=empty_teacher, user=empty_user)


@manager_profile.route('/create_teacher', methods=['POST'])
def create_teacher():
    log_request_info(request)

    if not valid_session(session):
        return redirect(url_for('auth.login'))

blueprints/student_profile.py
from flask import Blueprint, render_template, session, url_for, redirect

from app import app
from models.grade import Grade
from models.user import Role
from validators import valid_session

student_profile = Blueprint('student_profile', __name__)


@student_profile.route('/student_profile')
def profile():
    if not valid_session(session):
        return redirect(url_for('auth.login'))

    user_id = session['user_id']
    user_role = session['user_role']
    username = session['username']

    if user_role != Role.Student:
        return redirect(url_for('main.index'))

    app.logger.info(f"Пользователь {user_id}:{username} зашел в профиль студента")

    grades = Grade.get_grades(user_id)

    grade_map = dict()
    for grade in grades:
        year = grade['academic_year']
        if year not in grade_map:
            grade_map[year] = dict()
        semester = grade['semester']
        if semester not in grade_map[year]:
            grade_map[year][semester] = []
        grade_map[year][semester].append(grade)

    for y in sorted(grade_map.keys()):
        for s in sorted(grade_map[y].keys()):
            print(y, s, grade_map[y][s])

    return render_template('student_profile.html', grades=grade_map)

templates/base.html
<!doctype html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <meta name="viewport"
    content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/dataTables.bootstrap5.min.css') }}">

  <script src="{{ url_for('static', filename='js/jquery-3.3.1.slim.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery-3.5.1.js') }}"></script>
  <script src="{{ url_for('static', filename='js/jquery.dataTables.min.js') }}"></script>

  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Успеваемость</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
          aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link" href="/">Главная страница</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/profile">Профиль</a>
            </li>
          </ul>
        </div>

        <ul class="navbar-nav ms-md-auto">
          <li class="nav-item">
            <a class="nav-link" href="/logout">Выход</a>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <main>
    {% block body %}{% endblock %}
  </main>

  <footer>

  </footer>



  <script src="{{ url_for('static', filename='js/dataTables.bootstrap5.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
</body>

</html>

templates/group_discipline_list.html
{% set group_id = group.id %}
{% set group_name = group.group_name %}

<h1>Дисциплины для группы {{ group_name }}</h1>

<div class="row mt-4">
  <button type="button" class="btn btn-primary col-1" id="back-btn" onclick="loadGroups()">Назад</button>
  <button class="btn btn-primary col-1" type="button" id="create-btn" onclick="openGroupDisciplineForCreate({{ group_id }})">Создать</button>
</div>

<table class="group-table table table-bordered mt-4">
  <thead>
    <tr>
      <th scope="col">Дисциплина</th>
      <th scope="col">Год</th>
      <th scope="col">Семестр</th>
      <th scope="col">Преподаватель</th>
      <th scope="col">Редактирование</th>
    </tr>
  </thead>
  <tbody>

    {% for item in items %}
    {% set group_discipline_id = item['id'] %}
    {% set discipline_name = item['discipline_name'] %}
    {% set year = item['year'] %}
    {% set semester = item['semester'] %}
    {% set teacher_name = item['teacher_name'] %}

    <tr>
      <td>{{ discipline_name }}</td>
      <td>{{ year }}</td>
      <td>{{ semester }}</td>
      <td>{{ teacher_name }}</td>
      <td>
        <button class="btn btn-primary" type="button" id="edit-{{ group_discipline_id }}"
          onclick="deleteGroupDiscipline({{ group_id }}, {{ group_discipline_id }})">Удалить</button>
      </td>
    </tr>
    {% endfor %}

  </tbody>
</table>

templates/group_edit.html
<form id="edit-form" class="col-10">
  <fieldset>
    <button type="button" class="btn btn-primary mb-4 col-2" onclick="loadGroups()">Назад</button>

    <div class="form-group mt-4">
      <label for="name-input">Название группы</label>
      <input type="text" name="name" class="form-control" id="name-input" value="{{ group.group_name }}" 
             placeholder="Введите название группы (буквы русского алфавита, пробел)" minlength="1" maxlength="32" required="" pattern="^(?=[А-Яа-яЁё].*)[0-9А-Яа-яЁё\s-]+$"
             oninvalid="validateText('name-input')">

    </div>

    <div class="form-group mt-4">
      <label for="course-input">Курс</label>
      <input type="number" class="form-control" name="course" placeholder="Введите курс" id="course-input" value="{{ group.course }}"
                             value="1" min="1" max="8" required="" 
                             oninvalid="this.setCustomValidity('Пожалуйста, введите корректное значение курса')" 
                             oninput="setCustomValidity('')">
    </div>

    <div class="form-group">
      <label for="spec-select" class="form-label mt-4">Специальность</label>
      <select class="form-select" id="spec-select">

        {% for spec in specs %}
          {% if spec['id'] == group.speciality_id %}
            <option selected value="{{ spec['id'] }}">{{ spec['speciality_name'] }}</option>
          {% else %}
            <option value="{{ spec['id'] }}">{{ spec['speciality_name'] }}</option>
          {% endif %} 
        {% endfor %}

      </select>
    </div>

    {% if group.id == 0 %}
      <button type="button" class="btn btn-primary mt-4 col-2" id="ok-button" onclick="createGroup()">ОК</button>
    {% else %}
      <button type="button" class="btn btn-primary mt-4 col-2" id="ok-button" onclick="editGroup({{ group.id }})">ОК</button>
    {% endif %} 

  </fieldset>
</form>

templates/group_grades.html
<div class="container">
  <div id="accordion">

    {% for student, infos in group_grades|dictsort %}
    {% set idx = loop.index %}

    <div class="card">
      <div class="card-header" id="heading{{ idx }}">
        <h5 class="mb-0">
          <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
            <input type="radio" class="btn-check" id="btn{{ idx }}" autocomplete="off" data-toggle="collapse"
              data-target="#collapse{{ idx }}" aria-expanded="true" aria-controls="collapse{{ idx }}">
            <label class="btn btn-primary" for="btn{{ idx }}">{{ student }}</label>
          </div>
        </h5>
      </div>

      <div id="collapse{{ idx }}" class="collapse" aria-labelledby="heading{{ idx }}" data-parent="#accordion">
        <table class="grades-table table table-bordered">
          <thead>
            <tr>
              <th scope="col">Оценка</th>
              <th scope="col">Дата</th>
            </tr>
          </thead>
          <tbody>

            {% for info in infos %}
            <tr>
              <td>{{ info['grade'] }}</td>
              <td>{{ info['date'] }}</td>
            </tr>
            {% endfor %}
            
          </tbody>
        </table>
      </div>
    </div>

    {% endfor %}

  </div>
</div>

templates/index.html
{% extends 'base.html' %}

{% block title %}
Главная страница
{% endblock %}

{% block body %}
<div class="container col-md-4">
  
    <h1>Добро пожаловать в электронный дневник!</h1>

</div>



{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}
Вход
{% endblock %}

{% block body %}
<div class="container col-md-4">
  
    <form method="POST" action="/login">
        <fieldset>
          <div class="form-group">
            <label for="inputLogin1" class="form-label mt-4">Логин</label>
            <input type="text" name="login" class="form-control" id="inputLogin1" placeholder="Введите логин" minlength="1" maxlength="128" required="" oninvalid="this.setCustomValidity('Пожалуйста, введите логин')" oninput="setCustomValidity('')">
          </div>

          <div class="form-group">
            <label for="inputPassword1" class="form-label mt-4">Пароль</label>
            <input type="password" name="password" class="form-control" id="inputPassword1" placeholder="Введите пароль" required="" oninvalid="this.setCustomValidity('Пожалуйста, введите пароль')" oninput="setCustomValidity('')">
          </div>
          
          <button type="submit" class="login-btn btn btn-primary btn-lg col-12">Войти</button>
        </fieldset>
      </form>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger alert alert-dismissible alert-secondary mt-2">
                {{ messages[0] }}
            </div>
        {% endif %}
    {% endwith %}

</div>
{% endblock %}

templates/login2fa.html
{% extends 'base.html' %}

{% block title %}
Вход
{% endblock %}

{% block body %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-12">
      <div class="jumbotron text-center p-4">
        <h2>Введите одноразовый пароль с вашего устройства</h2>
      </div>
    </div>

    {% if need_register %}

    <div class="col-lg-5">
      <form>
        <div>
          <h5>Вы первый раз вошли в учетную запись, завершите регистрацию.</h5>
          <ul>
            <li>Загрузите <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=en&gl=US" target="_blank">Google Authenticator</a> на ваш мобильный телефон.</li>
            <li>Создайте новый аккаунт, отсканировав QR-код.</li>
            <li>Войдите в учетную запись с помощью одноразового пароля.</li>
          </ul>
        </div>
        <p><img id="qrcode" src="{{ url_for('auth.qrcode2fa') }}"></p>
      </form>
    </div>

    {% endif %} 

    <div class="col-lg-7">
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      {% for category, message in messages %}
      <div class="alert alert-{{ category }}" role="alert">
        {{ message }}
      </div>
      {% endfor %}
      {% endif %}
      {% endwith %}
      <form method="POST">
        <div class="form-group">
          <label for="otp">Одноразовый пароль</label>
          <input type="hidden" name="secret" value="{{ secret }}" required>
          <input type="number" class="form-control" id="otp" name="otp" required>
        </div>
        <div class="text-center">
          <button type="submit" class="btn btn-primary">Войти</button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

templates/manager_profile.html
{% extends 'base.html' %}

{% block title %}
Главная страница
{% endblock %}

{% block body %}

<div class="row">
    <div class="col-2">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link" href="#" onClick="loadSpecialities()">Специальности</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#" onClick="loadDisciplines()">Дисциплины</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="#" onClick="loadTeachers()">Преподаватели</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#" onClick="loadGroups()">Группы</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#" onClick="loadStudents()">Студенты</a>
            </li>
        </ul>
    </div>
    <div class="col-10">
        <div id="status-holder">
        </div>
    
        <div class="container" id="view">
        </div>
    </div>
</div>

<script src="{{ url_for('static', filename='js/manager_profile.js') }}"></script>

{% endblock %}

templates/register_teacher.html
    <form method="POST" class="col-11">
        <fieldset>
            <div class="form-group">
                <label class="col-form-label mt-4" for="input-year">Фамилия</label>
                <input type="text" class="form-control" placeholder="Введите фамилию" id="input-last-name" required>
            </div>

            <div class="form-group">
                <label class="col-form-label mt-4" for="input-year">Имя</label>
                <input type="text" class="form-control" placeholder="Введите имя" id="input-first-name" required>
            </div>

            <div class="form-group">
                <label class="col-form-label mt-4" for="input-year">Отчество</label>
                <input type="text" class="form-control" placeholder="Введите отчество" id="input-patronymic" required>
            </div>

            <button id="reg-teacher-btn" type="button" class="login-btn btn btn-primary btn-lg col-12">Зарегистрировать</button>

        </fieldset>
      </form>

templates/speciality_edit.html
<form id="edit-form" class="col-10">
  <fieldset>
    <button type="button" class="btn btn-primary mb-4 col-2" onclick="loadSpecialities()">Назад</button>

    <div class="form-group mt-4">
      <label for="name-input">Название</label>
      <input type="text" name="name" class="form-control" id="name-input" value="{{ item.speciality_name }}" 
             placeholder="Введите название специальности (буквы русского и английского алфавита, пробел)" minlength="1" maxlength="64" required="" pattern="^(?=[A-Za-zА-Яа-яЁё].*)[A-Za-zА-Яа-яЁё\s-]+$"
             oninvalid="validateText('name-input')">
    </div>

    {% if item.id == 0 %}
      <button type="button" class="btn btn-primary mt-4 col-2" id="ok-button" onclick="createSpeciality()">ОК</button>
    {% else %}
      <button type="button" class="btn btn-primary mt-4 col-2" id="ok-button" onclick="editSpeciality({{ item.id }})">ОК</button>
    {% endif %} 

  </fieldset>
</form>

templates/speciality_list.html
<h1>Специальности</h1>

<button class="btn btn-primary mt-4" type="button" id="create-btn" onclick="openSpecialityForCreate()">Создать</button>
<table class="speciality-table table table-bordered">
    <thead>
      <tr>
        <th scope="col">Название</th>
        <th scope="col">Редактирование</th>
      </tr>
    </thead>
    <tbody>

    {% for item in items %}
        <tr>
        <td>{{ item['name'] }}</td>
        <td>
            <button class="btn btn-primary" type="button" id="edit-{{ item['id'] }}" onclick="openSpecialityForEdit({{ item['id'] }})">Изменить</button>
        </td>
        </tr>
    {% endfor %}

    </tbody>
  </table>

templates/student_list.html
<h1>Студенты</h1>

<button class="btn btn-primary mt-4" type="button" id="create-btn" onclick="openStudentForCreate()">Создать</button>
<table class="student-table table table-bordered">
    <thead>
      <tr>
        <th scope="col">Имя</th>
        <th scope="col">Группа</th>
        <th scope="col">Год поступления</th>
        <th scope="col">Редактирование</th>
      </tr>
    </thead>
    <tbody>
    {% for s in data %}
        <tr>
        <td>{{ s['name'] }}</td>
        <td>{{ s['group'] }}</td>
        <td>{{ s['date'] }}</td>
        <td>
            <button class="btn btn-primary" type="button" id="edit-{{ s['id'] }}" onclick="openStudentForEdit({{ s['id'] }})">Изменить</button>
        </td>
        </tr>
    {% endfor %}
    </tbody>
  </table>

templates/teacher_list.html
<h1>Преподаватели</h1>

<button class="btn btn-primary mt-4" type="button" id="create-btn" onclick="openTeacherForCreate()">Создать</button>
<table class="teacher-table table table-bordered">
    <thead>
      <tr>
        <th scope="col">Имя</th>
        <th scope="col">Редактирование</th>
      </tr>
    </thead>
    <tbody>

    {% for teacher in teachers %}
        <tr>
        <td>{{ teacher['name'] }}</td>
        <td>
            <button class="btn btn-primary" type="button" id="edit-{{ teacher['id'] }}" onclick="openTeacherForEdit({{ teacher['id'] }})">Изменить</button>
        </td>
        </tr>
    {% endfor %}

    </tbody>
  </table>